env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - standard-with-typescript
  - plugin:react/jsx-runtime
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react-hooks
rules:
  react/jsx-one-expression-per-line: 0
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .jsx
        - .tsx
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
settings:
  react:
    version: '18.2.0'
  import/resolver:
    typescript: []
